### ISSUE TITLE
建議修改

### ISSUE THREAD

**Issue by M-J-LIN** [JudgeGirl/JudgeNode#27]
$ chmod +x deploy_mySQL.sh
$ ./deploy_mysql.sh <database> <user> <password>
大小寫

$ python distribute_setup.py
未更新

root $ cd Judge-receiver/scripts
沒s

$ bower install
$ gulp build
以上皆須先NPM INSTALL BOWER,GULP

$ ./start
先安裝colorama by pip3
pip3 install colorama

$ node adduser.js nodejs judgegirl notpassword 0 judgegirl@judgegirl.org
參數有錯 nodejs adduser.js $1 $2 $3 $4
motto nname ename 沒有default值
須自行加入adduser.js

root $ cd Judge-receiver/scripts
root $ ./mount
./mount，每一次主機重新開啟 (例如斷電重開職主機後)，要重新執行這條指令

**Comment by morris821028** [comment]
1. 修正地一個安裝 MySQL 操作問題於  
 https://github.com/JudgeGirl/Judge-MySQL/tree/master/scripts
2. 將安裝 MySQL 於 python3 中的腳本，已經修改到   
https://github.com/JudgeGirl/Judge-sender/tree/master/scripts
3. 增加使用者的插入指令，已經修改預設的 MySQL table 的設定  
https://github.com/JudgeGirl/Judge-MySQL/blob/master/CREATE_TABLE.sql
4. 重新啟動需要重新 mount 為正常操作，否則請撰寫在開機時執行的腳本。
