### ISSUE TITLE
Submission number

### ISSUE THREAD

**Issue by pangfengliu** [JudgeGirl/JudgeNode#3]
List the number of times the student has submitted a solution to a task.

**Comment by morris821028** [comment]
Example:

add information panel into the problem page.

```
AC ratio: 30% (30  / 100)
Subtask 1 (20%): 1.0s
Subtask 2 (20%): 1.0s
Subtask 3 (20%): 1.0s
Subtask 4 (20%): 1.0s
Subtask 5 (20%): 1.0s 
```

**Comment by pangfengliu** [comment]
The example above  is good, but what I meant was the number of times THIS PARTICULAR student made submission to a problem.

**Comment by morris821028** [comment]
I don't how to design the page layout with the number of times & particular student.

maybe can find the submission according problem id from user page, but the number of submission hasn't show on page.
- open the rank list page, find the user name to load user information.
- For example, URL like http://140.112.31.208/user/1
- click the problem id, then redirect the page, such as http://140.112.31.208/submissions?pid=10005&uid=1

On the other hand, it just implements the filter on submission URL.

**Comment by morris821028** [comment]
so, the admin will the special page like ...

```
tool-bar
---
My Status, Status, Statistic, Submission Report
                              ^^^^^^^^^^^^^^^^^
```

and show like the scoreboard ?
