### ISSUE TITLE
Announcement made by other adminstrators

### ISSUE THREAD

**Issue by pangfengliu** [JudgeGirl/JudgeNode#4]
Is there any way for other SA to make accounment? It seems that the current mechaism is to make change on a web document directly.

**Comment by morris821028** [comment]
@sinmaplewing , i need help.

**Comment by pangfengliu** [comment]
Is there any package (for announcements) that we can use?

**Comment by morris821028** [comment]
I think that markdown format will be more helpful to edit content than the text editor plugin, so I will install the markdown render plugin into the system.

**Comment by morris821028** [comment]
now, this feature has been add into the system. Please check it completely as you want.
